name: Purge PR images

on:
  pull_request_target:
    types:
      - closed
    paths:
      - "**/*"
      - "!.github/**" # Important: Exclude PRs related to .github from auto-run
      - "!.github/workflows/**" # Important: Exclude PRs related to .github from auto-run


permissions:
  contents: read
  packages: write

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      githubfolder: ${{ steps.filter.outputs.githubfolder }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3.0.1
        id: filter
        with:
          filters: |
            githubfolder:
              - '.github/**'

  purge-pr-package:
    name: Delete images from ghcr.io when PR is closed
    needs: check_paths
    if: needs.check_paths.outputs.githubfolder == 'false'
    runs-on: ubuntu-latest

    steps:
      - uses: chipkent/action-cleanup-package@v1.0.3
        id: cleanup
        continue-on-error: true
        with:
          package-name: ${{ github.event.repository.name }}
          tag: pr-${{ github.event.pull_request.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/delete-package-versions@v5
        if: job.steps.cleanup.status == success()
        name: Delete untagged images from ghcr.io
        continue-on-error: true
        with:
          package-name: "teslamate"
          package-type: "container"
          min-versions-to-keep: 0
          delete-only-untagged-versions: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
